name: Snyk Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '18 9 * * 3'

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read           # Para checkout
      security-events: write  # Para subir SARIF a GitHub
      actions: read            # Solo necesario para repos privados
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Instalar Snyk CLI
      run: npm install -g snyk

    - name: Autenticarse con Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Construir imagen Docker
      run: docker build -t my-app .

    - name: Escanear imagen Docker y generar SARIF
      run: snyk container test my-app --file=Dockerfile --sarif-file-output=snyk.sarif || true

    - name: Subir resultados a GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif
